title: 'Bitdevs SG'
tagline: 'BitDevs is a community1 for those interested in discussing and participating in the research and development of Bitcoin and related protocols.'

menu:
  - {name: 'About', url: '/about.html'}
  - {name: 'Meetup', url: 'https://www.meetup.com/bitdevs-sg/', external: true}
  - {name: 'Twitter', url: 'https://twitter.com/sgbitdevs',external: true}
  - {name: 'Telegram', url: 'https://t.me/sgbitdevs',external: true}
